"""Typed agent models: tool results, execution context, grants and registry rows.

Standard library only. The provider-level types (ToolCall, ChatResponse, the
normalized tool schema) belong to ``providers.models`` and are reused, not
redefined here.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from enum import Enum
from types import MappingProxyType
from typing import Any, Awaitable, Callable, Mapping, Optional



class Trust(str, Enum):
    """Where a tool result's text came from, which decides how the model sees it.

    trusted             server-generated by Nova (control results, errors,
                        grant refusals): sent as is.
    household_data      Home Assistant state and Nova's own stores: sent as is;
                        entity names and states are data, not instructions.
    untrusted_external  free text from outside the house (web pages, email,
                        calendars, documents, camera vision, specialist
                        webhooks): always fenced as quoted data.
    """

    TRUSTED = "trusted"
    HOUSEHOLD_DATA = "household_data"
    UNTRUSTED_EXTERNAL = "untrusted_external"


@dataclass(frozen=True, slots=True)
class ToolResult:
    """One tool call's outcome inside the dispatcher and the turn loop.

    ``content`` is exactly the text the executor produced (a JSON string for
    every Nova tool). ``to_message()`` is the single place a result becomes a
    provider-facing tool message: trusted and household results are sent
    byte for byte, untrusted external ones inside a fresh prompt fence.
    ``metadata`` is bounded, non-sensitive bookkeeping only (never arguments,
    entity state or provider text)."""

    content: str
    is_error: bool = False
    code: Optional[str] = None
    trust: Trust = Trust.TRUSTED
    metadata: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        if not isinstance(self.content, str):
            raise TypeError("ToolResult.content must be a string")
        if len(self.metadata) > 8:
            raise ValueError("ToolResult.metadata is limited to 8 entries")
        object.__setattr__(self, "metadata", MappingProxyType(dict(self.metadata)))

    @classmethod
    def error(cls, code: str, message: str, **extra: Any) -> "ToolResult":
        """A server-generated refusal or failure, in the agent's usual
        ``{"error": ...}`` shape."""
        return cls(json.dumps({"error": message, **extra}), is_error=True, code=code)

    @classmethod
    def from_executor(cls, content: str, trust: Trust) -> "ToolResult":
        """Wrap an executor's JSON string. ``is_error`` mirrors a top-level
        ``error`` key, the one error signal every executor already uses."""
        is_error = False
        try:
            parsed = json.loads(content)
            is_error = isinstance(parsed, dict) and "error" in parsed
        except (TypeError, ValueError):
            pass
        return cls(content, is_error=is_error, code="tool_error" if is_error else None,
                   trust=trust)

    def model_text(self, tool_name: str) -> str:
        """The text the model receives for this result."""
        if self.trust is not Trust.UNTRUSTED_EXTERNAL:
            return self.content
        from ..prompt_fence import fence
        return fence(
            self.content,
            label="TOOL_RESULT",
            noun=(f"is the output of the {tool_name} tool, quoted from an "
                  f"external source"),
            callback_noun="quoted tool output",
        )

    def to_message(self, call_id: str, tool_name: str) -> dict:
        """The OpenAI-shaped tool history entry for this result."""
        return {"role": "tool", "tool_call_id": call_id,
                "content": self.model_text(tool_name)}


# Where a run came from. Only a live conversation has a person behind it.
ORIGIN_CONVERSATION = "conversation"
ORIGIN_HEADLESS = "headless"
ORIGIN_DELEGATED = "delegated"


@dataclass(frozen=True, slots=True)
class ToolExecutionContext:
    """Who and what a tool call runs for. Built once per turn, never guessed:
    ``user_id`` and ``device_id`` are None when the request has none."""

    origin: str = ORIGIN_CONVERSATION
    depth: int = 0
    device_id: Optional[str] = None
    user_id: Optional[str] = None
    hass_api: Any = field(default=None, repr=False, compare=False)
    user_input: Any = field(default=None, repr=False, compare=False)

    @classmethod
    def for_turn(cls, *, user_input: Any, hass_api: Any, depth: int,
                 headless: bool) -> "ToolExecutionContext":
        if depth > 0:
            origin = ORIGIN_DELEGATED
        elif headless:
            origin = ORIGIN_HEADLESS
        else:
            origin = ORIGIN_CONVERSATION
        return cls(
            origin=origin,
            depth=depth,
            device_id=getattr(user_input, "device_id", None) or None,
            user_id=getattr(getattr(user_input, "context", None), "user_id", None) or None,
            hass_api=hass_api,
            user_input=user_input,
        )

    @property
    def has_requester(self) -> bool:
        return bool(self.device_id or self.user_id)


@dataclass(frozen=True, slots=True)
class ToolGrant:
    """The tools one run may call. Enforced at dispatch; also the only source
    for the tool list offered to the model and the prompt's tool guidance.

    ``tools`` is None only for the main conversational grant, which also
    admits Home Assistant's own LLM API tools."""

    name: str
    tools: Optional[frozenset] = None
    include_ha_tools: bool = False

    @property
    def is_main(self) -> bool:
        return self.tools is None

    def allows(self, tool_name: str) -> bool:
        return self.tools is None or tool_name in self.tools


@dataclass(frozen=True, slots=True)
class RegisteredTool:
    """One registry row: a tool's executor and what it is allowed to do."""

    name: str
    executor: Optional[Callable[..., Awaitable[str]]]
    capability: str
    mutates: bool = False          # changes the home or Nova's safety posture
    persists: bool = False         # writes a persistent store
    network: bool = False          # reaches beyond Home Assistant
    trust: Trust = Trust.HOUSEHOLD_DATA
